cell_states: 3

cell_symbols:
  empty: 0
  tree:  1
  fire:  2
cell_type: 'uint8'

grid_shape:
  n_row: 100
  n_col: 100

ca_params:
  p_fire: 0.033
  p_tree: 0.333

# Modifier's effects
# Change FIRE to EMPTY
effects:
  fire: 'empty'

actions:
  up_left:    1
  up:         2
  up_right:   3
  left:       4
  not_move:   5
  right:      6
  down_left:  7
  down:       8
  down_right: 9
action_type: 'uint8'

# Steps that the Cellular Automaton remains idle.
max_freeze: 2

rewards:
  per_empty: 0.0
  per_tree:  1.0
  per_fire: -1.0

# Cellular Automata rendering options.
cell_colors:
  empty: '#ddd1d3ff' # Gray
  tree:  '#a9c499ff' # Green
  fire:  '#dfa4a0ff' # Red

plot_title: 'Forest Fire Environment'
plot_font:  'Lato' 
